// Generated by CoffeeScript 1.12.7
(function() {
  var make_preview, mathjaxDebug;

  make_preview = function(elt) {
    var card, hidden_css, hide_preview, id, ref, show_preview, url, visible_css;
    ref = elt.attr("href").split("#"), url = ref[0], id = ref[1];
    card = $("<div class='card'>\n  <div class='holder'>\n    <p>Placeholder</p>\n  </div>\n</div>");
    card.css({
      width: "35vw",
      padding: "1.5rem",
      position: "fixed",
      top: "1.5rem",
      right: "1.5rem",
      boxSizing: "border-box",
      maxHeight: "calc(100vh - 3rem)",
      overflow: "hidden",
      boxShadow: "0 0 1rem #e6e6e6",
      backgroundColor: "white"
    });
    visible_css = {
      visibility: "visible",
      opacity: 1,
      transform: "translateX(0em)",
      transition: "all 0.3s linear"
    };
    hidden_css = {
      visibility: "hidden",
      opacity: 0,
      transform: "translateX(1em)",
      transition: "all 0.3s linear 0.5s"
    };
    card.css(hidden_css);
    elt.css({
      textDecoration: "underline solid #0a0a0a",
      textDecorationSkip: "ink",
      transition: "background-color 0.3s linear"
    });
    show_preview = function() {
      elt.css({
        backgroundColor: "#d3d3d3"
      });
      return card.css(visible_css);
    };
    hide_preview = function() {
      elt.css({
        backgroundColor: "#d3d3d300"
      });
      return card.css(hidden_css);
    };
    return card.find(".holder").load(url + (" [id='" + id + "']"), function(response, status, jxXHR) {
      console.log("XHR status:", status, url, id);
      if (status === "success" || status === "notmodified") {
        console.log("success!");
        console.log("elt:", $(elt));
        $("body").append(card);
        card.find("p, .p").css({
          textAlign: "left"
        });
        card.find("section").css({
          marginBottom: "0"
        });
        card.find("section").children().last().css({
          marginBottom: "0"
        });
        MathJax.Hub.Queue(["Typeset", MathJax.Hub, card[0]]);
        elt.on("mouseenter", show_preview);
        return elt.on("mouseleave", hide_preview);
      }
    });
  };

  mathjaxDebug = function() {
    MathJax.Hub.signal.Interest(function(message) {
      return console.log("*", message);
    });
    return MathJax.Hub.Register.StartupHook("End Process", function() {
      var i, jax, len, ref, results;
      console.log("list of jaxes:");
      ref = MathJax.Hub.getAllJax();
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        jax = ref[i];
        results.push(console.log("jax:", jax));
      }
      return results;
    });
  };

  $(function() {
    var elt, i, len, ref, results;
    ref = $("a.preview");
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      elt = ref[i];
      results.push(make_preview($(elt)));
    }
    return results;
  });

}).call(this);
